version : "3.9"

services : 
  db : 
    image :  mysql:8.0 
    volumes : 
      - .docker/database:/sql
      - .docker/database/data:/var/lib/mysql
    environment : 
      MYSQL_USER :  tiago 
      MYSQL_PASSWORD :  123456
      MYSQL_DATABASE : projetotrainee 
      MYSQL_ROOT_PASSWORD : 123456
    ports : 
      -  "4000:3306"
    networks : 
      -  backend_net

  app : 
    container_name :  backend
    build :  . 
    volumes : 
      -  ./app:/var/www/html
    depends_on : 
      -  db
    networks : 
      -  backend_net
    environment :
      DATABASE_URL : mysql://root:123456@db:3306/projetotrainee?serverVersion=8.0

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/html:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8000:80'
    networks:
      - backend_net
    depends_on:
      - app


networks : 
  backend_net :